### ISSUE TITLE
Change units for rate from sat/(W*h) to sat/(kW*h)

### ISSUE THREAD

**Issue by AndySchroder** [DistributedCharge/Dashboard#6]
Can't settle anything less than 1 sat on chain, so it doesn't make sense to have non-integer values of sat. Also the energy industry prices everything in kW*hour, so using that will make rate be around 500 sat/(kW*hour) to 4,000 sat/(kW*hour) at current prices and integers can be used in tables and axis labels without loosing any needed precision.

Keep values of power and energy in terms of W and W*hours for now. Those make physical sense as floating point numbers and also current demos will be under 1,600 W so kW won't be as simple to read. Will likely want to change to kW and kW*hours in the future in either a manual or automatic way, but don't want to decide how to do that now.

**Comment by asherp** [comment]
The current fix is that I check each variable for [sat/Wh] units, and if they exist I convert the array to [sat/kWh] See:

https://github.com/DistributedCharge/Dashboard/blob/4cf218c437068859b62b2d26fe4c1a0975d08977/dcharge/utils.py#L49
